language: python
matrix:
  include:
    - name: "Python 3.7 on Xenial Linux"
      dist: xenial
      python: '3.7'
    - name: "Python 3.6 on Xenial Linux"
      dist: xenial
      python: '3.6'
    - name: "Python 3.5 on Xenial Linux"
      dist: xenial
      python: '3.5'
    - name: "Python 3.7 on MacOS"
      os: osx
      osx_image: xcode10.2
      language: shell
    - name: "Python 3.6 on MacOS"
      os: osx
      osx_image: xcode9.4
      language: shell
    - name: "Python 3.7 on Windows"
      os: windows
      language: shell
      before_install: choco install python
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
branches:
  only:
    - master
install:
  - pip3 install -r requirements.txt
script: pytest
